[project]
name = "sanaap-backend-challenge-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Saeed", email = "saeed.adelpour99@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
sanaap-backend-challenge-api = "sanaap_backend_challenge_api:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
