[project]
name = "sanaap-backend-challenge-api"
version = "0.1.0"
description = "Insurance document management API built with Django REST framework"
readme = "README.md"
authors = [
    { name = "Saeed", email = "saeed.adelpour99@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "django>=5.2,<5.3",
    "djangorestframework>=3.16,<4",
    "minio>=7.2,<8",
    "psycopg[binary]>=3.1.8,<4",
    "python-decouple>=3.8",
    "urllib3>=2,<3",
]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]

[tool.ruff]
target-version = "py311"
line-length = 88
src = ["src"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP", "B", "TID252"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"
