# Generated by Django 5.2.17 on 2026-09-25 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_filereplacement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("upload_file", "Can upload files"),
                    ("replace_file", "Can replace files"),
                    ("download_file", "Can download files"),
                    ("destroy_file", "Can destroy files"),
                ],
            },
        ),
    ]
