# Generated by Django 5.2.17 on 2026-09-25 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_file_deleted_at_file_deleted_by_file_purged_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="filereplacement",
            name="replaced_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file_replacements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
